# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 06:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20160719_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, verbose_name=[django.core.validators.RegexValidator(message='Invalid Mobile Number', regex='^[789]\\d{9}$')]),
        ),
    ]
