# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import drive.models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(upload_to=drive.models.path_and_rename),
        ),
    ]
