# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import drive.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20160719_0633'),
        ('drive', '0002_auto_20160722_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to=drive.models.path_and_rename)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(upload_to=b''),
        ),
    ]
