# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_auto_20160730_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrelation',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookrelation',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='bookrelation',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookRelation',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
